# Generated by Django 3.2 on 2021-09-23 10:58

import apps.common.mixins.general
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to=apps.common.mixins.general.model_directory, verbose_name='header image')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
