# Generated by Django 3.2 on 2021-09-23 10:57

import apps.common.mixins.general
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.common.mixins.general.model_directory, verbose_name='avatar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ['name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created=True, editable=False, max_length=1024, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.mixins.general.model_directory, verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='summary')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-start_date', '-end_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('icon', models.ImageField(upload_to=apps.common.mixins.general.model_directory, verbose_name='icon')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'ordering': ['title', 'url'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created=True, editable=False, max_length=1024, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.author', verbose_name='author')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['author', 'title'],
            },
        ),
    ]
