name: Islam Ayman CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3-alpine
        env:
          POSTGRES_USER: "islam"
          POSTGRES_PASSWORD: "yourStrong(!)Password"
          POSTGRES_DB: "islam"
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/testing.txt

      - name: Test with black
        run: |
          python -m black --check .

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: "config.settings.testing"
          SECRET_KEY: "SECRET_KEY"
          DATABASE: "postgres"
          POSTGRES_HOST: "localhost"
          POSTGRES_PORT: "5432"
          POSTGRES_DB: "islam"
          POSTGRES_USER: "islam"
          POSTGRES_PASSWORD: "yourStrong(!)Password"
        run: |
          python manage.py collectstatic --noinput
          pytest
